import configparser
import os
import shutil
import sys

Import("env")  # noqa: F821 — PlatformIO injects SCons env

SECTION = "secrets"
# (local.ini key, C macro name)
KEYS = [
    ("wifi_ssid",     "DESKNEST_WIFI_SSID"),
    ("wifi_pass",     "DESKNEST_WIFI_PASS"),
    ("tokennest_url", "DESKNEST_TOKENNEST_STATUS_URL"),
]


def _warn(msg):
    sys.stderr.write("\n" + "=" * 60 + "\n")
    sys.stderr.write("[pio_local_config] " + msg + "\n")
    sys.stderr.write("=" * 60 + "\n\n")
    sys.stderr.flush()


def _ensure_local_ini(project_dir):
    local_ini = os.path.join(project_dir, "platformio.local.ini")
    example_ini = os.path.join(project_dir, "platformio.local.ini.example")
    if os.path.exists(local_ini):
        return
    if not os.path.exists(example_ini):
        _warn("platformio.local.ini.example missing. "
              "Your build will use defaults (no WiFi, no TokenNest).")
        return
    shutil.copy2(example_ini, local_ini)
    _warn(
        "Created platformio.local.ini from platformio.local.ini.example.\n"
        ">>> Please edit it and fill in your real WiFi SSID/password and TokenNest URL.\n"
        ">>> This file is .gitignore'd and will NOT be committed."
    )


def _strip_quotes(s):
    """configparser preserves quotes literally; strip a single matched pair."""
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('"', "'"):
        return s[1:-1]
    return s


def _c_escape(s):
    """Escape a string for use inside a C double-quoted string literal."""
    # Order matters: backslash must be escaped first, so \\ doesn't get
    # double-escaped by the subsequent quote/escape replacements.
    return (s
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t"))


def _read_secrets(local_ini_path):
    cp = configparser.ConfigParser()
    cp.read(local_ini_path, encoding="utf-8-sig")
    if SECTION not in cp:
        return {}
    section = cp[SECTION]
    return {
        local_key: _strip_quotes(section.get(local_key, "")).strip()
        for local_key, _macro in KEYS
    }


def _write_header(project_dir, secrets):
    """Write include/generated/secrets.h with C #define directives.

    Only macros whose value is non-empty are written. An empty value is
    intentionally omitted so the #ifndef guard in src/config.h provides
    the default (empty string). This keeps the graceful-degradation path
    (NVS / demo data) when local.ini is unconfigured.
    """
    gen_dir = os.path.join(project_dir, "include", "generated")
    os.makedirs(gen_dir, exist_ok=True)
    header_path = os.path.join(gen_dir, "secrets.h")

    lines = [
        "/* Auto-generated by scripts/pio_local_config.py — do not edit manually */",
        "#ifndef GENERATED_DESK_NEST_SECRETS_H",
        "#define GENERATED_DESK_NEST_SECRETS_H",
        "",
    ]
    for local_key, macro in KEYS:
        value = secrets.get(local_key, "")
        if value:
            escaped = _c_escape(value)
            lines.append(f'#define {macro} "{escaped}"')
        # else: omit; #ifndef in config.h provides empty-string default

    lines.append("")
    lines.append("#endif /* GENERATED_DESK_NEST_SECRETS_H */")
    lines.append("")

    content = "\n".join(lines)
    old_content = None
    if os.path.exists(header_path):
        with open(header_path, "r", encoding="utf-8") as f:
            old_content = f.read()

    if old_content != content:
        # Atomic write: write to .tmp then rename (avoids partial file on crash)
        tmp = header_path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp, header_path)
        print(f"[pio_local_config] wrote {header_path}  ({len(secrets)} key(s))")
    else:
        print(f"[pio_local_config] unchanged {header_path}  ({len(secrets)} key(s))")
    return header_path


def _remove_stale_firmware_outputs(project_dir, header_path):
    """Remove rebuildable firmware outputs when secrets are newer.

    PlatformIO/SCons sometimes recompiles objects but keeps an older linked
    firmware image for upload. If the generated credentials header is newer
    than the final firmware artifacts, delete those artifacts so the linker
    must produce a fresh image.
    """
    build_dir = os.path.join(project_dir, ".pio", "build", "DeskNest")
    if not os.path.isdir(build_dir) or not os.path.exists(header_path):
        return

    header_mtime = os.path.getmtime(header_path)
    for name in ("firmware.elf", "firmware.bin", "firmware.map"):
        path = os.path.join(build_dir, name)
        if os.path.exists(path) and os.path.getmtime(path) < header_mtime:
            os.remove(path)
            print(f"[pio_local_config] removed stale {path}")


def _inject(project_dir, local_ini_path, secrets):
    # Only inject for the firmware env. Skip test / other envs.
    if env.get("PIOENV") != "DeskNest":
        return

    header_path = _write_header(project_dir, secrets)
    _remove_stale_firmware_outputs(project_dir, header_path)

    # -include forces the header before every TU, regardless of include order.
    # We also add -I include so the path resolves even if include is not
    # already in the flags (it is in platformio.ini, but this is idempotent).
    env.Append(CXXFLAGS=["-include", header_path])
    env.Append(CPPPATH=["include"])

    # Make the generated credentials part of the firmware dependency graph.
    # Without this, some PlatformIO upload flows can reuse an older
    # .pio/build/.../firmware.bin even after platformio.local.ini changes.
    for target in ("$BUILD_DIR/${PROGNAME}.elf",
                   "$BUILD_DIR/${PROGNAME}.bin",
                   "upload"):
        env.Depends(target, header_path)
        env.Depends(target, local_ini_path)

    # Log which macros are now defined. Never print secrets in plaintext.
    for local_key, macro in KEYS:
        value = secrets.get(local_key, "")
        if local_key == "wifi_pass" and value:
            status = f"(set, len={len(value)})"
        else:
            status = f'"{_c_escape(value)}"' if value else "(empty -> #ifndef default)"
        print(f"[pio_local_config]   {macro} = {status}")


# --- entry point ---
_ensure_local_ini(env["PROJECT_DIR"])

local_ini = os.path.join(env["PROJECT_DIR"], "platformio.local.ini")
project_dir = env["PROJECT_DIR"]

if os.path.exists(local_ini):
    try:
        secrets = _read_secrets(local_ini)
    except (configparser.Error, OSError) as e:
        _warn(f"failed to read secrets from {local_ini}: {e}\n"
              f">>> Building without personal config (will use NVS / demo data).")
        secrets = {}
    _inject(project_dir, local_ini, secrets)
